// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function Branch():Promise<string>;

export function BranchExists(arg1:string):Promise<boolean>;

export function Branches(arg1:string):Promise<Array<git.GitBranch>>;

export function Checkout(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function Diff(arg1:string,arg2:boolean):Promise<git.GitDiff>;

export function DiffAll(arg1:boolean):Promise<string>;

export function DiscardChanges(arg1:Array<string>):Promise<void>;

export function GetRepoPath():Promise<string>;

export function GetRoot(arg1:string):Promise<string>;

export function Init(arg1:string):Promise<void>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function Log(arg1:number):Promise<Array<git.GitCommit>>;

export function Pull():Promise<void>;

export function Push():Promise<void>;

export function SetRepoPath(arg1:string):Promise<void>;

export function Stage(arg1:Array<string>):Promise<void>;

export function Stash(arg1:string):Promise<void>;

export function StashPop():Promise<void>;

export function Status(arg1:string):Promise<git.GitStatus>;

export function Summary(arg1:string):Promise<git.GitSummary>;

export function Unstage(arg1:Array<string>):Promise<void>;
