// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branch() {
  return window['go']['git']['GitService']['Branch']();
}

export function BranchExists(arg1) {
  return window['go']['git']['GitService']['BranchExists'](arg1);
}

export function Branches() {
  return window['go']['git']['GitService']['Branches']();
}

export function Checkout(arg1) {
  return window['go']['git']['GitService']['Checkout'](arg1);
}

export function Commit(arg1) {
  return window['go']['git']['GitService']['Commit'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['git']['GitService']['CreateBranch'](arg1);
}

export function Diff(arg1, arg2) {
  return window['go']['git']['GitService']['Diff'](arg1, arg2);
}

export function DiffAll(arg1) {
  return window['go']['git']['GitService']['DiffAll'](arg1);
}

export function DiscardChanges(arg1) {
  return window['go']['git']['GitService']['DiscardChanges'](arg1);
}

export function GetRepoPath() {
  return window['go']['git']['GitService']['GetRepoPath']();
}

export function GetRoot(arg1) {
  return window['go']['git']['GitService']['GetRoot'](arg1);
}

export function Init(arg1) {
  return window['go']['git']['GitService']['Init'](arg1);
}

export function IsGitRepo(arg1) {
  return window['go']['git']['GitService']['IsGitRepo'](arg1);
}

export function Log(arg1) {
  return window['go']['git']['GitService']['Log'](arg1);
}

export function Pull() {
  return window['go']['git']['GitService']['Pull']();
}

export function Push() {
  return window['go']['git']['GitService']['Push']();
}

export function SetRepoPath(arg1) {
  return window['go']['git']['GitService']['SetRepoPath'](arg1);
}

export function Stage(arg1) {
  return window['go']['git']['GitService']['Stage'](arg1);
}

export function Stash(arg1) {
  return window['go']['git']['GitService']['Stash'](arg1);
}

export function StashPop() {
  return window['go']['git']['GitService']['StashPop']();
}

export function Status(arg1) {
  return window['go']['git']['GitService']['Status'](arg1);
}

export function Summary(arg1) {
  return window['go']['git']['GitService']['Summary'](arg1);
}

export function Unstage(arg1) {
  return window['go']['git']['GitService']['Unstage'](arg1);
}
