// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultShell() {
  return window['go']['terminal']['TerminalService']['GetDefaultShell']();
}

export function IsRunning() {
  return window['go']['terminal']['TerminalService']['IsRunning']();
}

export function StartTerminal(arg1) {
  return window['go']['terminal']['TerminalService']['StartTerminal'](arg1);
}

export function Startup(arg1) {
  return window['go']['terminal']['TerminalService']['Startup'](arg1);
}

export function StopTerminal() {
  return window['go']['terminal']['TerminalService']['StopTerminal']();
}
