// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetDefaultShell():Promise<string>;

export function IsRunning():Promise<boolean>;

export function StartTerminal(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopTerminal():Promise<void>;
