// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function Close():Promise<void>;

export function CreateFile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetEventChannel():Promise<any>;

export function GetFileTree(arg1:string):Promise<fs.FileNode>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SetWatcher(arg1:fs.FileWatcher):Promise<void>;

export function Unwatch(arg1:string):Promise<void>;

export function Watch(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
