// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['fs']['FileService']['Close']();
}

export function CreateFile(arg1, arg2) {
  return window['go']['fs']['FileService']['CreateFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['fs']['FileService']['DeleteFile'](arg1);
}

export function GetEventChannel() {
  return window['go']['fs']['FileService']['GetEventChannel']();
}

export function GetFileTree(arg1) {
  return window['go']['fs']['FileService']['GetFileTree'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['fs']['FileService']['ReadFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['fs']['FileService']['RenameFile'](arg1, arg2);
}

export function SetWatcher(arg1) {
  return window['go']['fs']['FileService']['SetWatcher'](arg1);
}

export function Unwatch(arg1) {
  return window['go']['fs']['FileService']['Unwatch'](arg1);
}

export function Watch(arg1) {
  return window['go']['fs']['FileService']['Watch'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['fs']['FileService']['WriteFile'](arg1, arg2);
}
