// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function BranchExists(arg1) {
  return window['go']['main']['App']['BranchExists'](arg1);
}

export function ClearChatMessages(arg1) {
  return window['go']['main']['App']['ClearChatMessages'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CreateChatSession() {
  return window['go']['main']['App']['CreateChatSession']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitGitAndSave(arg1) {
  return window['go']['main']['App']['InitGitAndSave'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SetCurrentProject(arg1) {
  return window['go']['main']['App']['SetCurrentProject'](arg1);
}
