// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {config} from '../models';

export function AddProject(arg1:string):Promise<project.Project>;

export function BranchExists(arg1:string):Promise<boolean>;

export function ClearChatMessages(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function CreateChatSession():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function Greet(arg1:string):Promise<string>;

export function InitGitAndSave(arg1:string):Promise<project.Project>;

export function ListProjects():Promise<Array<project.Project>>;

export function RemoveProject(arg1:number):Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function SetCurrentProject(arg1:string):Promise<void>;
