// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function BranchExists(arg1:string):Promise<boolean>;

export function CreateBranch(arg1:string):Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function Greet(arg1:string):Promise<string>;

export function ResetSettings():Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;
