// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1: string): Promise<string>;
export function GetSettings(): Promise<string>;
export function SaveSettings(arg1: string): Promise<void>;
export function ResetSettings(): Promise<void>;
