// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branch() {
    return window['go']['main']['GitService']['Branch']();
}

export function Branches() {
    return window['go']['main']['GitService']['Branches']();
}

export function Checkout(arg1) {
    return window['go']['main']['GitService']['Checkout'](arg1);
}

export function Commit(arg1) {
    return window['go']['main']['GitService']['Commit'](arg1);
}

export function Diff(arg1, arg2) {
    return window['go']['main']['GitService']['Diff'](arg1, arg2);
}

export function DiffAll(arg1) {
    return window['go']['main']['GitService']['DiffAll'](arg1);
}

export function DiscardChanges(arg1) {
    return window['go']['main']['GitService']['DiscardChanges'](arg1);
}

export function GetRepoPath() {
    return window['go']['main']['GitService']['GetRepoPath']();
}

export function GetRoot(arg1) {
    return window['go']['main']['GitService']['GetRoot'](arg1);
}

export function Init(arg1) {
    return window['go']['main']['GitService']['Init'](arg1);
}

export function IsGitRepo(arg1) {
    return window['go']['main']['GitService']['IsGitRepo'](arg1);
}

export function Log(arg1) {
    return window['go']['main']['GitService']['Log'](arg1);
}

export function Pull() {
    return window['go']['main']['GitService']['Pull']();
}

export function Push() {
    return window['go']['main']['GitService']['Push']();
}

export function SetRepoPath(arg1) {
    return window['go']['main']['GitService']['SetRepoPath'](arg1);
}

export function Stage(arg1) {
    return window['go']['main']['GitService']['Stage'](arg1);
}

export function Stash(arg1) {
    return window['go']['main']['GitService']['Stash'](arg1);
}

export function StashPop() {
    return window['go']['main']['GitService']['StashPop']();
}

export function Status(arg1) {
    return window['go']['main']['GitService']['Status'](arg1);
}

export function Summary(arg1) {
    return window['go']['main']['GitService']['Summary'](arg1);
}

export function Unstage(arg1) {
    return window['go']['main']['GitService']['Unstage'](arg1);
}
