// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branch(): Promise<string>;
export function Branches(): Promise<Array<GitBranch>>;
export function Checkout(arg1: string): Promise<void>;
export function Commit(arg1: string): Promise<void>;
export function Diff(arg1: string, arg2: boolean): Promise<GitDiff>;
export function DiffAll(arg1: boolean): Promise<string>;
export function DiscardChanges(arg1: Array<string>): Promise<void>;
export function GetRepoPath(): Promise<string>;
export function GetRoot(arg1: string): Promise<string>;
export function Init(arg1: string): Promise<void>;
export function IsGitRepo(arg1: string): Promise<boolean>;
export function Log(arg1: number): Promise<Array<GitCommit>>;
export function Pull(): Promise<void>;
export function Push(): Promise<void>;
export function SetRepoPath(arg1: string): Promise<void>;
export function Stage(arg1: Array<string>): Promise<void>;
export function Stash(arg1: string): Promise<void>;
export function StashPop(): Promise<void>;
export function Status(arg1: string): Promise<GitStatus>;
export function Summary(arg1: string): Promise<GitSummary>;
export function Unstage(arg1: Array<string>): Promise<void>;

// Go 结构体对应的 TypeScript 接口
export interface GitBranch {
    name: string;
    current: boolean;
    remote?: string;
    ahead: number;
    behind: number;
}

export interface GitCommit {
    hash: string;
    shortHash: string;
    message: string;
    author: string;
    email: string;
    date: string;
}

export interface GitDiff {
    path: string;
    oldPath?: string;
    content: string;
    isNew: boolean;
    isDeleted: boolean;
    isBinary: boolean;
}

export interface GitFileStatus {
    path: string;
    indexStatus: string;
    worktreeStatus: string;
    staged: boolean;
}

export interface GitStatus {
    branch: string;
    ahead: number;
    behind: number;
    modified: Array<GitFileStatus>;
    added: Array<GitFileStatus>;
    deleted: Array<GitFileStatus>;
    untracked: Array<GitFileStatus>;
    renamed: Array<GitFileStatus>;
    conflicted: Array<GitFileStatus>;
    staged: Array<GitFileStatus>;
    isClean: boolean;
}

export interface GitSummary {
    branch: string;
    ahead: number;
    behind: number;
    modifiedCount: number;
    addedCount: number;
    deletedCount: number;
    untrackedCount: number;
    stagedCount: number;
    totalChanges: number;
    isClean: boolean;
}
